spring:
   profiles:
     active: local
   application:
     name: unlimits_auth
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/unlimits_auth
     username: root
     password: root
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         
   mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: mail.smtp2go.com #smtp.gmail.com
    username: clavisdigital #nikhilraj0123467@gmail.com
    protocol: smtp
    password: PoqAKFiNmCSIm5Xy #keqx xjod sicl qtzy
    test-connection: 'false'
    port: '587'
   db:
     datajson:
       upload: true
springdoc:
   swagger-ui:
      path: /api/swagger-ui.html
      disable-swagger-default-url: true
      api-docs.path: /v3/api-docs
      paths-to-match: /v3/api-docs
openapi:
  service:
      url: http://51.79.159.7:8080/auth
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
# HTTP Server (Tomcat) Port
server: 
  port: 2222
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true